#!/usr/bin/bash

wc -l ps*js Simple*js
echo "Running jshint ..."
jshint psflib.js psflib.test.js
if [ $? -eq 0 ]; then
  echo "Running jest ..."
  jest psflib.test.js bin-pack.test.js
fi
echo "Done."
